apiVersion: datadoghq.com/v2alpha1
kind: DatadogAgent
metadata:
  name: datadog
spec:
  global:
    clusterName: storedog-k8s
    site: datadoghq.com
    credentials:
      apiSecret:
        secretName: datadog-secret
        keyName: api-key
      appSecret:
        secretName: datadog-secret
        keyName: app-key
  features:
    orchestratorExplorer:
      enabled: true
    liveContainerCollection:
      enabled: true
    apm:
      enabled: true
    eventCollection:
      collectKubernetesEvents: true
    logCollection:
      enabled: true
      containerCollectAll: true
    npm:
      enabled: true
  override:
    nodeAgent:
      image:
        tag: 7.67.0
    clusterAgent:
      image:
        tag: 7.67.0
