apiVersion: datadoghq.com/v2alpha1
kind: DatadogAgent
metadata:
  name: datadog
spec:
  global:
    clusterName: storedog-k8s
    site: datadoghq.com
    kubelet:
      tlsVerify: false
    credentials:
      apiSecret:
        secretName: datadog-secret
        keyName: api-key
      appSecret:
        secretName: datadog-secret
        keyName: app-key
  features:
    orchestratorExplorer:
      enabled: true
    liveContainerCollection:
      enabled: true
    apm:
      enabled: true
    eventCollection:
      collectKubernetesEvents: true
    logCollection:
      enabled: true
      containerCollectAll: true
    npm:
      enabled: true
  override:
    nodeAgent:
      tolerations:
        - effect: NoSchedule
          key: node-role.kubernetes.io/control-plane
          operator: Exists
      extraConfd:
        configMap:
          name: datadog-checks
      volumes:
        - hostPath:
            path: /etc/kubernetes/pki/etcd
          name: etcd-certs
        - name: disable-etcd-autoconf
          emptyDir: {}
      containers:
        agent:
          volumeMounts:
            - name: etcd-certs
              mountPath: /host/etc/kubernetes/pki/etcd
              readOnly: true
            - name: disable-etcd-autoconf
              mountPath: /etc/datadog-agent/conf.d/etcd.d
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: datadog-checks
data:
  etcd-config: |-
    ad_identifiers:
      - etcd
    init_config:
    instances:
      - prometheus_url: https://%%host%%:2379/metrics
        tls_ca_cert: /host/etc/kubernetes/pki/etcd/ca.crt
        tls_cert: /host/etc/kubernetes/pki/etcd/server.crt
        tls_private_key: /host/etc/kubernetes/pki/etcd/server.key
  nginx_ingress_controller-config: |-
    ad_identifiers:
      - ingress-nginx
    init_config:
    instances:
      - nginx_status_url: http://%%host%%:18080/nginx_status
        prometheus_url: http://%%host%%:10254/metrics
        collect_nginx_histograms: true
    logs:
      - service: controller
        source: nginx-ingress-controller
