apiVersion: v1
kind: Service
metadata:
  name: discounts
spec:
  ports:
    - port: 2814
      targetPort: 2814
      name: http
  selector:
    app: store-discounts
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: discounts
  labels:
    app: store-discounts
    team: discounts
spec:
  replicas: 1
  selector:
    matchLabels:
      app: store-discounts
  template:
    metadata:
      labels:
        app: store-discounts
        team: discounts
      annotations:
        ad.datadoghq.com/discounts.logs: '[{"source": "python"}]'
    spec:
      volumes:
        - name: apmsocketpath
          hostPath:
            path: /var/run/datadog/
      initContainers:
        - name: wait-for-db
          image: busybox:1.37.0
          command: ['sh', '-c', 'until nc -z postgres 5432; do echo waiting for postgres; sleep 2; done;']
      containers:
        - name: discounts
          image: ${REGISTRY_URL}/discounts:${SD_TAG}
          ports:
            - containerPort: 2814
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: storedog-secrets
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: storedog-config
                  key: POSTGRES_USER
            - name: POSTGRES_HOST
              valueFrom:
                configMapKeyRef:
                  name: storedog-config
                  key: DB_HOST
            - name: DD_SERVICE
              value: store-discounts
            - name: DD_VERSION
              value: ${DD_VERSION_DISCOUNTS}
            - name: DD_RUNTIME_METRICS_ENABLED
              value: "true"
            - name: DD_PROFILING_ENABLED
              value: "true"
            - name: DD_PROFILING_ALLOCATION_ENABLED
              value: "true"
            - name: DD_PROFILING_TIMELINE_ENABLED
              value: "true"
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "200m"
          volumeMounts:
            - name: apmsocketpath
              mountPath: /var/run/datadog
