apiVersion: v1
kind: Service
metadata:
  name: ads-python
spec:
  ports:
    - port: 3030
      targetPort: 3030
      name: http
  selector:
    app: store-ads-python
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ads-python
  labels:
    app: store-ads-python
    team: advertisements
spec:
  replicas: 1
  selector:
    matchLabels:
      app: store-ads-python
  template:
    metadata:
      labels:
        app: store-ads-python
        team: advertisements
      annotations:
        ad.datadoghq.com/ads-python.logs: '[{"source": "python"}]'
    spec:
      volumes:
        - name: apmsocketpath
          hostPath:
            path: /var/run/datadog/
      containers:
        - name: ads-python
          image: ${REGISTRY_URL}/ads:${SD_TAG}
          ports:
            - containerPort: 3030
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: storedog-secrets
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: storedog-config
                  key: POSTGRES_USER
            - name: POSTGRES_HOST
              valueFrom:
                configMapKeyRef:
                  name: storedog-config
                  key: DB_HOST
            - name: DD_SERVICE
              value: store-ads-python
            - name: DD_VERSION
              value: ${DD_VERSION_ADS}
            - name: DD_LOGS_INJECTION
              value: "true"
            - name: DD_RUNTIME_METRICS_ENABLED
              value: "true"
            - name: DD_PROFILING_ENABLED
              value: "true"
            - name: DD_PROFILING_ALLOCATION_ENABLED
              value: "true"
            - name: DD_PROFILING_TIMELINE_ENABLED
              value: "true"
          resources:
            requests:
              memory: "256Mi"
              cpu: "200m"
            limits:
              memory: "512Mi"
              cpu: "400m"
          volumeMounts:
            - name: apmsocketpath
              mountPath: /var/run/datadog
