apiVersion: v1
kind: Service
metadata:
  name: service-proxy
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
      name: http
  selector:
    app: service-proxy
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-proxy
  labels:
    app: service-proxy
    team: edge
    tags.datadoghq.com/service: service-proxy
    tags.datadoghq.com/version: ${DD_VERSION_NGINX}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-proxy
  template:
    metadata:
      labels:
        app: service-proxy
        team: edge
        tags.datadoghq.com/service: service-proxy
        tags.datadoghq.com/version: ${DD_VERSION_NGINX}
      annotations:
        ad.datadoghq.com/service-proxy.logs: '[{"source": "nginx"}]'
        ad.datadoghq.com/service-proxy.checks: |
          {
            "nginx": {
              "init_config": {},
              "instances": [{"nginx_status_url": "http://%%host%%:81/nginx_status/"}]
            }
          }
    spec:
      volumes:
        - name: apmsocketpath
          hostPath:
            path: /var/run/datadog/
      containers:
        - name: service-proxy
          image: ${REGISTRY_URL}/nginx:${SD_TAG}
          ports:
            - containerPort: 80
          env:
            - name: NGINX_RESOLVER
              value: "kube-dns.kube-system.svc.cluster.local"
            - name: DD_ENV
              valueFrom:
                configMapKeyRef:
                  name: storedog-config
                  key: DD_ENV
            - name: DD_SERVICE
              value: service-proxy
            - name: DD_VERSION
              value: ${DD_VERSION_NGINX}
            - name: DD_TRACE_AGENT_URL
              value: 'unix:///var/run/datadog/apm.socket'
            # A/B testing ads services (optional)
            - name: ADS_A_UPSTREAM
              value: "ads:3030"
            - name: ADS_B_UPSTREAM
              value: "ads-python:3030"
            - name: ADS_B_PERCENT
              value: "50"
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "200m"
          volumeMounts:
            - name: apmsocketpath
              mountPath: /var/run/datadog
