name: Backend

permissions: {}

on:
  push:
    branches: [ main ]
    paths:
      - services/backend/**
  workflow_dispatch:

defaults:
  run:
    working-directory: backend

jobs:

  build:

    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to GHCR
      id: login-ghcr
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: ./services/backend
        platforms: linux/amd64,linux/arm64
        push: true
        tags: ghcr.io/datadog/storedog/backend:latest

