name: Frontend

on:
  push:
    branches: [ main, devin.ford/fe-testing ]
    paths:
      - services/frontend/**
  workflow_dispatch:
    branches: [ main, devin.ford/fe-testing ]

defaults:
  run:
    working-directory: frontend

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Login to ECR
      id: login-ecr
      uses: docker/login-action@v1
      with:
        registry: public.ecr.aws
        username: ${{ secrets.AWS_ACCESS_KEY_ID }}
        password: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    - name: Build and push AMD
      uses: docker/build-push-action@v4
      with:
        context: ./services/frontend
        platforms: linux/amd64
        push: true
        tags: ${{ secrets.PUBLIC_ECR_REGISTRY }}/storedog/frontend:test5

    - name: Build and push ARM
      uses: docker/build-push-action@v4
      continue-on-error: true
      with:
        context: ./services/frontend
        platforms: linux/arm64
        push: true
        tags: ${{ secrets.PUBLIC_ECR_REGISTRY }}/storedog/frontend:test5-arm

