name: Publish release

permissions: {}

# Only release on a new tag that is a version number.
on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

jobs:

  publish_service_containers:
    name: Publish all images
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        id: login-ecr
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Download, Tag, and Push Service Images
        run: |
          TAG=${GITHUB_REF/refs\/tags\//}

          IMAGES=(
            ghcr.io/DataDog/storedog/backend
            ghcr.io/DataDog/storedog/discounts
            ghcr.io/DataDog/storedog/ads
            ghcr.io/DataDog/storedog/ads-java
            ghcr.io/DataDog/storedog/attackbox
            ghcr.io/DataDog/storedog/auth
            ghcr.io/DataDog/storedog/nginx
            ghcr.io/DataDog/storedog/frontend
            ghcr.io/DataDog/storedog/dbm
            ghcr.io/DataDog/storedog/postgres
          )

          for i in "${IMAGES[@]}"
          do
            echo "$i"

            docker pull "$i":latest
            docker tag "$i":latest "$i":$TAG
            docker push "$i":$TAG

          done

          echo "All done"

